# 1. Installing and Importing Dependencies

In [22]:
# Make sure you are using the rl-tutorial environment
# !pip install 'stable-baselines3[extra]'

In [23]:
!pip install pyglet

In [24]:
import os
import gym 
# openAI gym , allows us to build environemnt and work with preexisting environemnts

# from stable_baselines3 import PPO 

# from stable_baselines3.common.vec_env import DummyVecEnv 
# # Allows you to train your agent on different environments. 

# from stable_baselines3.common.evaluation import evaluate_policy 
# Makes it easier to test out our model. Get average reward over number episodes.


In [25]:
gym.__version__

'0.24.1'

# 2. Loading the environment

In [41]:
env = gym.make('CarRacing-v1')

# obs = env.reset()



In [26]:
# environment_name = "CarRacing-v2"
# env = gym.make(environment_name)
import time
env = gym.make('CarRacing-v1')

obs = env.reset()

for step in range(500):
    action = env.action_space.sample()
    obs, reward, done, info = env.step(action)
    print(obs)
    env.render()
    time.sleep(0.001)
    

env.close()
print("done")


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[100 202 100]
  [100 202 100]
  [100 202 100]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[100 202 100]
  [100 202 100]
  [100 202 100]
  ...
  [  0   0   0

In [17]:
import random 

class ObservationWrapper(gym.ObservationWrapper):
    def __init__(self, env):
        super().__init__(env)
    
    def observation(self, obs):
        # Normalise observation by 255
        return obs / 255.0

class RewardWrapper(gym.RewardWrapper):
    def __init__(self, env):
        super().__init__(env)
    
    def reward(self, reward):
        # Clip reward between 0 to 1
        return np.clip(reward, 0, 1)
    
class ActionWrapper(gym.ActionWrapper):
    def __init__(self, env):
        super().__init__(env)
    
    def action(self, action):
        if action == 3:
            return random.choice([0,1,2])
        else:
            return action

Box([-1.  0.  0.], 1.0, (3,), float32)


In [ ]:
env = gym.make('CarRacing-v1',render_mode="human")
wrapped_env = ObservationWrapper(env)




In [6]:
episodes = 5 
for episode in range(1, episodes+1):
  state = env.reset()
  # gives the initial observation for the environment 
  
  done = False
  score = 0

  while not done:
    env.render()
    action = env.action_space.sample()
    n_state, reward, done, info = env.step(action)
    score += reward
  print ("Episode: {} Score: {}".format(episode, score))


env.close()
print("Window should be closed")

Episode: 1 Score: -27.797833935018403
Episode: 2 Score: -27.272727272727522
Episode: 3 Score: -40.62500000000067
Episode: 4 Score: -29.32862190812759
Episode: 5 Score: -34.21052631579002
Window should be closed


: 

In [6]:
env.action_space

Box([-1.  0.  0.], 1.0, (3,), float32)

In [7]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [8]:
env.reset()
env.step(1)

(array([ 0.03135575,  0.16955484, -0.02874754, -0.25300589]), 1.0, False, {})

## Understanding the environment

https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py

In [9]:
env.action_space.sample()

0

In [10]:
env.observation_space.sample()

array([-3.6388180e-01, -9.4070830e+37, -2.3769679e-02, -2.2716420e+38],
      dtype=float32)

# Train an RL Model

In [11]:
# Make your directories first!
log_path = os.path.join("Training", "Logs")

In [12]:
log_path

'Training/Logs'

In [13]:
env = gym.make(environment_name)

In [14]:
env = DummyVecEnv([lambda: env]) # Wrapper for a non-vectorized environment
model = PPO('MlpPolicy', env, verbose=1, tensorboard_log=log_path) # multilayer perceptron policy

Using cpu device


In [15]:
model.learn(total_timesteps=20000)

Logging to Training/Logs/PPO_3
-----------------------------
| time/              |      |
|    fps             | 6607 |
|    iterations      | 1    |
|    time_elapsed    | 0    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 4372        |
|    iterations           | 2           |
|    time_elapsed         | 0           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.007815102 |
|    clip_fraction        | 0.0979      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.686      |
|    explained_variance   | -0.00131    |
|    learning_rate        | 0.0003      |
|    loss                 | 8.37        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0151     |
|    value_loss           | 52.1        |
-----------------------------------------
---

# 4. Save and Reload Model

In [16]:
PPO_Path = os.path.join("Training", "Saved Models", "PPO_Model_Cartpole")

In [17]:
model.save(PPO_Path)

In [18]:
del model

In [19]:
model = PPO.load(PPO_Path, env=env)

In [20]:
model.learn(total_timesteps=20000)

Logging to Training/Logs/PPO_4
-----------------------------
| time/              |      |
|    fps             | 6669 |
|    iterations      | 1    |
|    time_elapsed    | 0    |
|    total_timesteps | 2048 |
-----------------------------
----------------------------------------
| time/                   |            |
|    fps                  | 4428       |
|    iterations           | 2          |
|    time_elapsed         | 0          |
|    total_timesteps      | 4096       |
| train/                  |            |
|    approx_kl            | 0.00487105 |
|    clip_fraction        | 0.021      |
|    clip_range           | 0.2        |
|    entropy_loss         | -0.525     |
|    explained_variance   | 0.0862     |
|    learning_rate        | 0.0003     |
|    loss                 | 27         |
|    n_updates            | 110        |
|    policy_gradient_loss | -0.000209  |
|    value_loss           | 24.2       |
----------------------------------------
---------------------

# 5. Evaluation

In [21]:
evaluate_policy(model, env, n_eval_episodes=10, render=True)

/Users/caydengwee/Coding/.virtualenvs/rl-tutorial/lib/python3.8/site-packages/stable_baselines3/common/evaluation.py:65: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


(200.0, 0.0)

# 6. Test Model

In [22]:
 episodes = 5 
for episode in range(1, episodes+1):
  obs = env.reset()
  # gives the initial observation for the environment 
  
  done = False
  score = 0

  while not done:
    env.render()
    action , _ = model.predict(obs) # Now USING MODEL HERE!
    obs, reward, done, info = env.step(action)
    score += reward
  print ("Episode: {} Score: {}".format(episode, score))


env.close()


Episode: 1 Score: [200.]
Episode: 2 Score: [200.]
Episode: 3 Score: [200.]
Episode: 4 Score: [200.]
Episode: 5 Score: [200.]


# 7. Viewing Logs in Tensorboard